import type { Transaction, ScheduledTransaction } from '../types';

const today = new Date();
const currentYear = today.getFullYear();
const currentMonth = String(today.getMonth() + 1).padStart(2, '0');

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    description: 'Salário Mensal',
    amount: 7500.0,
    type: 'income',
    date: `${currentYear}-${currentMonth}-05`,
    category_id: 'cat-salario',
    subcategory_id: 'sub-salario-principal',
    payment_method: 'Depósito em Conta',
    is_paid: true,
    notes: 'Pagamento referente ao mês atual',
  },
  {
    id: 'tx-2',
    description: 'Rendimento FIIs',
    amount: 420.5,
    type: 'income',
    date: `${currentYear}-${currentMonth}-15`,
    category_id: 'cat-investimentos',
    subcategory_id: 'sub-fiis',
    payment_method: 'Pix',
    is_paid: true,
  },
  {
    id: 'tx-3',
    description: 'Aluguel do Apê',
    amount: 1800.0,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-10`,
    category_id: 'cat-moradia',
    subcategory_id: 'sub-aluguel',
    payment_method: 'Pix',
    is_paid: true,
  },
  {
    id: 'tx-4',
    description: 'Supermercado Mensal',
    amount: 950.4,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-08`,
    category_id: 'cat-alimentacao',
    subcategory_id: 'sub-supermercado',
    payment_method: 'Cartão de Crédito',
    is_paid: true,
  },
  {
    id: 'tx-5',
    description: 'Conta de Energia',
    amount: 245.9,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-12`,
    category_id: 'cat-moradia',
    subcategory_id: 'sub-energia',
    payment_method: 'Débito Automático',
    is_paid: true,
  },
  {
    id: 'tx-6',
    description: 'Jantar Restaurante',
    amount: 185.0,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-14`,
    category_id: 'cat-alimentacao',
    subcategory_id: 'sub-restaurantes',
    payment_method: 'Cartão de Crédito',
    is_paid: true,
  },
  {
    id: 'tx-7',
    description: 'Posto de Gasolina',
    amount: 280.0,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-18`,
    category_id: 'cat-transporte',
    subcategory_id: 'sub-combustivel',
    payment_method: 'Pix',
    is_paid: true,
  },
  {
    id: 'tx-8',
    description: 'iFood Fim de Semana',
    amount: 92.5,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-20`,
    category_id: 'cat-alimentacao',
    subcategory_id: 'sub-ifood',
    payment_method: 'Cartão de Crédito',
    is_paid: true,
  },
  {
    id: 'tx-9',
    description: 'Farmácia Remédios',
    amount: 115.3,
    type: 'expense',
    date: `${currentYear}-${currentMonth}-22`,
    category_id: 'cat-saude',
    subcategory_id: 'sub-farmacia',
    payment_method: 'Pix',
    is_paid: true,
  },
];

export const MOCK_SCHEDULED: ScheduledTransaction[] = [
  {
    id: 'sch-1',
    description: 'Internet Fibra 500MB',
    amount: 149.9,
    type: 'expense',
    frequency: 'monthly',
    due_date: `${currentYear}-${currentMonth}-28`,
    category_id: 'cat-moradia',
    subcategory_id: 'sub-internet',
    is_active: true,
  },
  {
    id: 'sch-2',
    description: 'Mensalidade Academia',
    amount: 119.0,
    type: 'expense',
    frequency: 'monthly',
    due_date: `${currentYear}-${currentMonth}-30`,
    category_id: 'cat-saude',
    subcategory_id: 'sub-academia',
    is_active: true,
  },
  {
    id: 'sch-3',
    description: 'Assinatura Netflix & Spotify',
    amount: 79.8,
    type: 'expense',
    frequency: 'monthly',
    due_date: `${currentYear}-${currentMonth}-25`,
    category_id: 'cat-lazer',
    subcategory_id: 'sub-streaming',
    is_active: true,
  },
  {
    id: 'sch-4',
    description: 'Bônus de Projeto',
    amount: 1500.0,
    type: 'income',
    frequency: 'once',
    due_date: `${currentYear}-${currentMonth}-29`,
    category_id: 'cat-salario',
    subcategory_id: 'sub-bonus',
    is_active: true,
  },
];
